{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.jamesehart.lightlogger",
    "module": "lightlogger-java",
    "version": "2026.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "lightlogger-java-2026.1.0.jar",
          "url": "lightlogger-java-2026.1.0.jar",
          "size": 6781,
          "sha512": "0ba6c73cf0495a1dba94ca9b7c79fa4add039156d3a63c94e91bdef4f5780a884594259614053053249bea8432226c586d65a40b597acec43e49d2a43f368349",
          "sha256": "cc266a04e3ddb9b7551db7b4180504258a9426e10a386f1fb796b82d3e9d5272",
          "sha1": "f2438cb5baf9b471debec689fd743f18ab947b3b",
          "md5": "169b27e0a86beb80fed7d24d6d70a907"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lightlogger-java-2026.1.0.jar",
          "url": "lightlogger-java-2026.1.0.jar",
          "size": 6781,
          "sha512": "0ba6c73cf0495a1dba94ca9b7c79fa4add039156d3a63c94e91bdef4f5780a884594259614053053249bea8432226c586d65a40b597acec43e49d2a43f368349",
          "sha256": "cc266a04e3ddb9b7551db7b4180504258a9426e10a386f1fb796b82d3e9d5272",
          "sha1": "f2438cb5baf9b471debec689fd743f18ab947b3b",
          "md5": "169b27e0a86beb80fed7d24d6d70a907"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lightlogger-java-2026.1.0-sources.jar",
          "url": "lightlogger-java-2026.1.0-sources.jar",
          "size": 3606,
          "sha512": "59469347e2665293e792828bcefe90a99f2cd94ec1647844559ab4dfd516f049a86d03d93bfc02bc2826ea4c0ae1502e7217a03b39429dd318651046c0a17018",
          "sha256": "f2cbdc93b9f6b7b1fc8cb4a16541068219092f4cda46ab0240387f39230833fb",
          "sha1": "d9c85287f826ae75c9c5a727820c86251211e778",
          "md5": "8b76ba9716773228c1a2265c2f8201be"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lightlogger-java-2026.1.0-javadoc.jar",
          "url": "lightlogger-java-2026.1.0-javadoc.jar",
          "size": 75095,
          "sha512": "27d598b63aa204d33b8e1c93cb28bed01a7b80cab65e4be5be23c6e739f0e7c57cab36510ca5077b9fda6fe6f0acc28f86a8d51617e1c7e22ab386c867f62a65",
          "sha256": "dcc767a3e03c165df77869cc90f890a44428034ed8affb3ce8b53464318eaae6",
          "sha1": "4a02ba79dc05bf43ae0f5ac098ba1b76889caa91",
          "md5": "254e4f11b88d42b770109e6ac97c4b64"
        }
      ]
    }
  ]
}
