{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.jamesehart.lightlogger",
    "module": "lightlogger-java",
    "version": "2026.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "lightlogger-java-2026.1.0.jar",
          "url": "lightlogger-java-2026.1.0.jar",
          "size": 6781,
          "sha512": "02824b5907155aaac26180bc05f3e9e463c96c7bffbe0bcc75fa7dac44c23b2a04a9fd0aeebf4579f16298fb8a61c12857544d4f05b70368e32551d9584a7d2f",
          "sha256": "d9b37a2fd4c862612cffe0caa65b14755229d4375acf8be1b74ee30d2d1e063a",
          "sha1": "c89163146f3bc7935f390dee7615cbb4ee626835",
          "md5": "cebb6186d3a3aac2fb5951d0c3f90213"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lightlogger-java-2026.1.0.jar",
          "url": "lightlogger-java-2026.1.0.jar",
          "size": 6781,
          "sha512": "02824b5907155aaac26180bc05f3e9e463c96c7bffbe0bcc75fa7dac44c23b2a04a9fd0aeebf4579f16298fb8a61c12857544d4f05b70368e32551d9584a7d2f",
          "sha256": "d9b37a2fd4c862612cffe0caa65b14755229d4375acf8be1b74ee30d2d1e063a",
          "sha1": "c89163146f3bc7935f390dee7615cbb4ee626835",
          "md5": "cebb6186d3a3aac2fb5951d0c3f90213"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lightlogger-java-2026.1.0-sources.jar",
          "url": "lightlogger-java-2026.1.0-sources.jar",
          "size": 3606,
          "sha512": "6d5491a9437642f0823a014e776802818cc5b03fbef40b898ab02e1b3c021f9663397e659df088be0fb8058bdcdff365c9bf43d3a9f753d2d47b1d1cbeade7e7",
          "sha256": "33052252d65ad10c77285a2d36eb4b7a2ad1bba8cb85d0dc38b150c648a9e876",
          "sha1": "75329f5906ea3c4f3ed9c04382d1334bd7966d2e",
          "md5": "92a1839a37ea5bea697749560751da7f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lightlogger-java-2026.1.0-javadoc.jar",
          "url": "lightlogger-java-2026.1.0-javadoc.jar",
          "size": 75095,
          "sha512": "8211e6044aabe1b23d659384bb515d73b4e533d125ad181ce42e717e4d5518c84af398d432fbe2b22302425cb709fd7eb6e0c4ea783deafba655c0814d39782d",
          "sha256": "8bffba597f33808d998a1ad89697a435bac7de47865de56d3c2e2bcc9d522c3e",
          "sha1": "2202cf04f02471a741f6ba2bbd4e3034811e0299",
          "md5": "af33a74b6dbd22ea074004be60d4b648"
        }
      ]
    }
  ]
}
